name: SpoCo North West Time Trial Series
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "Gruntfile.js", "Gulpfile.js", "package.json", ".git", ".sass-cache", "modernizr-config.json","README.md","TODO.md","Gemfile","Gemfile.lock"]
#baseurl: /
#url: http://spoco-nw.dev
url: http://spoco-nw.org.uk
env: production
minify_html: false

sass:
    sass_dir: _scss
    style: compressed

gems:
  - octopress-minify-html
  - jekyll-assets

email: spoco.nw@gmail.com

hashtags: SpoCo,TimeTrial
